### ISSUE TITLE
Why the scanned binary content differs?

### ISSUE THREAD

**Issue by typelogic** [nayuki/QR-Code-generator#104]
This is with regards on generating a QR code with 2 segments having encodings: alphanumeric, bytes. Let us simulate the binary content with `dd if=/dev/random of=/tmp/buf64.dat bs=64 count=1`. During a QR scan, I need to exactly see the same 64 bytes. However, with mixed segments, I am seeing [EF BF BD](https://i.imgur.com/620iUT1.jpg) which are not in `buf64.dat`. I tested these both in your `Python` and `C++` demo test run. 

```python
from qrcodegen import *

def print_qr(qrcode):
    """Prints the given QrCode object to the console."""
    border = 1
    for y in range(-border, qrcode.get_size() + border):
        for x in range(-border, qrcode.get_size() + border):
            print(u"\u2588 "[1 if qrcode.get_module(x,y) else 0] * 2, end="")
        print()
    print()

# dd if=/dev/random of=/tmp/buf64.dat bs=64 count=1
# od -w32 -t x1z /tmp/buf64.dat
buf64 = bytearray(open("/tmp/buf64.dat","rb").read())

url = QrSegment.make_alphanumeric("HTTP://SOMEURL.COM")
buf64_segment = QrSegment.make_bytes(buf64)

segments = [
    url,
    buf64_segment
]

qr = QrCode.encode_segments(segments, QrCode.Ecc.LOW)
print_qr(qr)
```

If I comment out `url` from `segments`, I get exact `buf64.dat` contents in a QR scan.

![](https://i.imgur.com/620iUT1.jpg)

**Comment by nayuki** [comment]
* `EF BF BD` is the UTF-8 representation of the Unicode replacement character U+FFFD. My QR Code generator library has no logic to add the character U+FFFD. I assume that your QR Code scanner application is inserting it because it thinks it sees byte values that would be malformed if interpreted as Unicode text.
* My library behaves the same across all 6 supported languages. If you feed the same input data, you will get the same output data. Hence this is why you saw the same result in Python and C++.
* Tip - instead of using `dd` to generate a file and then reading it, you can generate random bytes within Python using methods like [`random.randbytes()`](https://docs.python.org/3/library/random.html#random.randbytes).
* Basically, my library follows your instructions exactly and puts 2 segments into the QR Code - one segment in alphanumeric mode with your URL, and one segment in byte mode with your 64 bytes of data. You can verify this tediously by using a debugging QR Code scanner like https://zxing.org/w/decode.jspx and https://qrlogo.kaarposoft.dk/qrdecode.html .
* Most QR Code scanners will convert every numeric/alphanumeric/kanji segment into Unicode characters, concatenate byte mode segments together, interpret byte sequences as UTF-8 characters, and concatenate all the Unicode characters together. In particular, most QR Code scanners will not let you access the raw sequence of segments, and most won't let you access the raw sequence of bytes either. So I believe you are suffering from an inadequate QR Code scanner software that forces the interpretation of bytes as UTF-8 characters, hence why you are getting U+FFFD. I do not have any suggestions or advice to give beyond this, because my library is doing the right thing and you need to manage how you want to scan the data.
