### ISSUE TITLE
Margin requirements

### ISSUE THREAD

**Issue by alsaleem00** [nayuki/QR-Code-generator#107]
This is a great software.
The standard calls for margin around code.
I suggest to add option to add the margin to result code.

Thanks.

**Comment by nayuki** [comment]
This library already supports the feature you are asking for. It is named "border". For example (Python):

```python
class QrCode:
    
    def to_svg_str(self, border)
```

The reason why I chose to make the border optional is because the user might have a page layout that already has white space surrounding the QR Code. In that case, it makes sense to not add more white border.

**Comment by alsaleem00** [comment]
I did not know it is available in python. I am using C code.
I am using it in embedded app. The result will be displayed in LCD.
Adding border will enforce the standard as I do not need to make a larger rectangle and then paint QR inside.

Thanks.

**Comment by nayuki** [comment]
You didn't mention the language at first. That was an important detail. The C library is very bare-bones because it expects the developer to be competent at manipulating numbers, memory, and graphics.

In the C code, you can use the demo program as an example of how to add a border: https://github.com/nayuki/QR-Code-generator/blob/8cbd1f506ac59406b18d13a199187c2756f2e06f/c/qrcodegen-demo.c#L300-L311

**Comment by alsaleem00** [comment]
Great. Thanks.

**Comment by ffreality** [comment]
For Unreal Engine 5, it has to be like this.
```
int32 Margin = Border * 2;
TArray<FColor> QR_Pixels_Raw;
QR_Pixels_Raw.Init(BlackColor, (QRSize + Margin) * (QRSize + Margin));
            
for (int32 x = 0; x < QRSize + 0; x++)
{
    for (int32 y = 0; y < QRSize + 0; y++)
    {
        int32 Index_Pixel = ((x + Border) + (y + Border) * (QRSize + Margin));
        FColor EachPixel = QRCode.getModule(x, y) ? WhiteColor : BlackColor;
        QR_Pixels_Raw[Index_Pixel] = EachPixel;
    }
}
```

WhiteColor and BlackColor is an Unreal Engine 5 FColor Struct (BGRA8) and TArray is std::vector's equivalent.
You sample won't work because UE5 doesn't accept negative index for array bounds.
