### ISSUE TITLE
Add new design

### ISSUE THREAD

**Issue by lilyntalmers** [nayuki/QR-Code-generator#113]
There are some QR Code generators out the but none of them can create new designs like [qrcode-monkey](https://www.qrcode-monkey.com/). Any plan to add support for that?

**Comment by nayuki** [comment]
My QR Code generator library provides the core functionality. It takes in text and produces a basic barcode.

I will not be considering artistic options because they greatly expand the scope of the problem while adding little value. They turn a solved problem into one that needs continual feature requests, updates, and support.

Please use [`QrCode.size`](https://github.com/nayuki/QR-Code-generator/blob/8518684c0f33d004fa93971be2c6a8eca3167d1e/java/src/main/java/io/nayuki/qrcodegen/QrCode.java#L211-L213) and [`QrCode.getModule(int x, int y)`](https://github.com/nayuki/QR-Code-generator/blob/8518684c0f33d004fa93971be2c6a8eca3167d1e/java/src/main/java/io/nayuki/qrcodegen/QrCode.java#L274-L285) provided by my library. Everything else like colors, gradients, rounded corners, logos, etc. are the responsibility of the user.
