### ISSUE TITLE
Rust: 1.7.0 not semver compatible with 1.6.0

### ISSUE THREAD

**Issue by casey** [nayuki/QR-Code-generator#117]
Thanks for the useful library!

We're using `qrcodegen` in Rust, and we were using `QrCode::to_svg_string` in 1.6.0. We noticed that was removed in 1.7.0, which makes 1.7.0 not backwards compatible with 1.6.0, so technically the version number should be bumped to 2.0.0, since it's a breaking change.

`cargo` expects crate versions to indicate semver compatibility, so, for example, if you have 1.6.0 in your `Cargo.toml` file, `cargo` will assume that 1.7.0 is compatible, and substitute it for 1.6.0 without confirmation, which in this case would break the build.

**Comment by nayuki** [comment]
Thanks for your kind feedback. You description is correct and I am sorry to have inconvenienced you.

As of now, I think your options are to either pin version 1.6.0 or copy the implementation of `QrCode.to_svg_string()` into your project.

Ever since my first crate release years ago, I was aware of Rust/Cargo's semantic versioning guidelines ([0](https://doc.rust-lang.org/cargo/reference/publishing.html?search=#publishing-a-new-version-of-an-existing-crate), [1](https://doc.rust-lang.org/cargo/reference/semver.html), [2](https://semver.org/)). I chose to disregard them because I felt that this version was not worthy of being called a 2.0 release:

* There were no "marketing-friendly" changes like a GUI revamp, major paradigm/architecture/algorithm shift, or major features being added/changed/removed.
* Perhaps 90% of the codebase is still identical to the previous release. This does not feel like a "major" release.
* I made a lot of changes in comments rather than code, and I removed the SVG API which I felt was *not* the focal point of this library. I have always implicitly urged developers to use `get_module(x, y)` to do custom painting to fit their graphics libraries, programming environment, and niche needs (like custom colors, non-square modules, logos, etc.).
* Based on the past history of this project and my other projects (too long to list), it's more common for me to make incompatible changes (e.g. renaming members, restructuring public fields, removing functionality) than strictly forward-compatible changes (e.g. adding functions/classes, adding overloads, adding optional parameters). I suspect this is because I reach feature-completeness pretty early, avoid scope creep and perpetual addition, but also have a strong inclination to revise and polish my code for clarity and simplicity.
* Essentially all my previous "minor" version updates had semver-violating changes as well:
	* v1.2.1 → v1.3.0: Changed Rust `u8` to `Mask` and `Version`.
	* v1.3.1 → v1.4.0: Changed the public API to throw `DataTooLongException` instead of whatever other mechanism was used before.
	* v1.4.0 → v1.5.0: Changed the penalty scoring algorithm in all languages; this still produces scannable QR Codes, but may select a different mask pattern so the results are not guaranteed to be bit-identical to the old version.
	* v1.5.0 → v1.6.0: Merged C++ source files, thus changing which headers a user would include.
	* v1.6.0 → v1.7.0: Moved `QrCode_MAX_VERSION` to `Version::MAX`, et cetera.

Even though v1.4 → v1.5 seems to be a semver-obeying change, problems can still happen due to Hyrum's law: All observable behaviors of the system will be depended on by somebody. So in a sense, every "minor" release of this library would actually be a "major" release, and I would be up to v7.0.0 or something by now if I followed the rules strictly.

**Comment by casey** [comment]
I think an issue is just the expectation that rust *tools* have with respect to semantic versioning. We ran into a problem not because we manually bumped a version, but because we did `cargo install --path path/to/our/project`. `cargo install` ignores a project's `Cargo.lock` file, and picks dependencies based on the semantic version specs in the `Cargo.toml`, so a Rust project that depends on `qrcodegen` without pinning to minor version and publishes to `crates.io` won't be installable with `cargo install` if `qrcodegen` publishes a backwards-incompatible minor version.

I definitely agree that bumping versions is annoying. I have a tool that's I've been working on for years that's still not `1.0.0`, because I don't want to have to bump the major version after each release.

**Comment by soenkehahn** [comment]
> Thanks for the useful library!

I second that, thanks for the library! :)

Not complying with semver rules is not only an issue with `cargo install`. You could also have a library that depends on `qrcodegen`, which by default will not have a `Cargo.lock` file. If the dependency is declared with `"1.6.0"` as the version, then (new) users of that library will get `1.7.0` once it's released, because `cargo` assumes semver compatibility. And then the library will fail to compile, if it runs into API breakages. The library authors should instead declare the `qrcodegen` dependency with version `"=1.6.0"`, which will avoid this issue.

Currently, users of `qrcodegen` are very unlikely to do that, since the fact that it doesn't comply with semver rules is not mentioned in the readme [here](https://crates.io/crates/qrcodegen). So I think mentioning these circumstances in the readme would be a good idea, to give users a better chance to understand the versioning of this library.

(Personally I also don't really see strong downsides to having more major version bumps. So if say in a year from now we have `qrcodegen` version `34.0.0`, I'd be totally fine with that. Whereas not complying with semver rules creates real problems for me as a user of `qrcodegen`. Because a lot of assumptions that `cargo` makes are broken and so it misbehaves.)

**Comment by nayuki** [comment]
Thanks to both casey and soenkehahn for your perspectives and explanations. I'll have to weigh the optics of a major version bump with other competing goals.

I skimmed the semver manifesto again, and found that they addressed some concerns in my mind (e.g. "Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.", "If even the tiniest backwards incompatible changes to the public API require a major version bump, won’t I end up at version 42.0.0 very rapidly?", ). So maybe my first mistake was not releasing the library as v0.x.y 😉.

I was hoping to reserve v2.0.0 for a major marketable feature instead of doing so for mechanistic API-compatibility reasons. (Although I have no plans to do so, a major feature would be like: QR Code Model 1, Micro QR Code, extensive output format support (PNG/SVG/GIF/BMP/JPEG/PS/PDF/whatever), artistic rendering styles.)

Note that I apply the versioning to this entire QR Code generator library project, not just to the Rust port. I insist on synchronizing the Java, Python, and Rust package version numbers, because I want users to know that they are getting the same *semantic* functionality from my work no matter which language they choose. Because of this, I have to take into consideration how version numbers are treated in Maven Central / mvn and PyPI/pip. I suspect no one else has a stronger semver convention than Rust/Cargo but I'm not sure. I also don't know to what extent major version bumps spook developers or keeps them interested.

Just nitpicking: soenkehahn, you should pin the readme version when you link to it, because this issue thread is publicly readable essentially forever. I myself started a habit only in the past few years where I use a commit hash instead of master when linking to GitHub-hosted files or lines of code.

**Comment by berkus** [comment]
> I would be up to v7.0.0 or something by now if I followed the rules strictly.

And that would be very bad exactly _why_?

What's wrong with getting to version 2.0 or 7.0 or 42.0?
