### ISSUE TITLE
io.nayuki.qrcodegen.QrCode.toSvgString(int) removed in 1.7.0

### ISSUE THREAD

**Issue by blacelle** [nayuki/QR-Code-generator#120]
Hello,

It seems native support for SVG is dropped with 1.7.0, requiring one to duplicate https://github.com/nayuki/QR-Code-generator/blob/4eb5dfaa25fe96b8e5e88fb779bf79f204ed0839/java/QrCodeGeneratorDemo.java#L227

Why not keeping these available in some helper method?

Thanks

**Comment by nayuki** [comment]
> Why not keeping these available in some helper method?

If my goal was to remove SVG code from the `QrCode` class, then sure I could have moved existing graphics stuff into a new utilities class.

But my goal was to entirely remove graphics support from the library because I see no clear winner on how QR Code symbols should be exported. The QR Code computation is timeless, but the graphics formats and environments will change by the year or decade. PNG and SVG were born some time ago, but may become unpopular in the next decades. I don't want to be part of this technology churn.

For reference, see:

* [Commit "Moved QrCodeGeneratorDemo.java out of the package because it's an informal demo and not a core library feature; this also simplifies the Maven build process."](https://github.com/nayuki/QR-Code-generator/commit/4eb5dfaa25fe96b8e5e88fb779bf79f204ed0839)
* [Issue #113](https://github.com/nayuki/QR-Code-generator/issues/113)
* [Issue #109](https://github.com/nayuki/QR-Code-generator/issues/109)
* [Issue #77](https://github.com/nayuki/QR-Code-generator/issues/77)
* [Issue #68](https://github.com/nayuki/QR-Code-generator/issues/68)
* [Issue #67](https://github.com/nayuki/QR-Code-generator/issues/67)
* [Issue #66](https://github.com/nayuki/QR-Code-generator/issues/66)
* [Issue #54](https://github.com/nayuki/QR-Code-generator/issues/54)
* [Issue #53](https://github.com/nayuki/QR-Code-generator/issues/53)
* [Pull request #50](https://github.com/nayuki/QR-Code-generator/pull/50)
* [Issue #46](https://github.com/nayuki/QR-Code-generator/issues/46)
* [Issue #34](https://github.com/nayuki/QR-Code-generator/issues/34)
* [Issue #33](https://github.com/nayuki/QR-Code-generator/issues/33)
* [Issue #27](https://github.com/nayuki/QR-Code-generator/issues/27)
* [Issue #17](https://github.com/nayuki/QR-Code-generator/issues/17)

**Comment by blacelle** [comment]
Fine.

**Comment by CICCIOSGAMINO** [comment]
Just grab the v1.8.0 Typecode, read the README and test the example with a toSvgString that does NOT work, so at least update the docs too ... with some easy example to run !
