### ISSUE TITLE
Width and Height in SVG files

### ISSUE THREAD

**Issue by olimaticer** [nayuki/QR-Code-generator#122]
First of all, thank you very much for this and the other libs you provided. 

I suggest to change 

	.append(String.format("<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" viewBox=\"0 0 %1$d %1$d\" stroke=\"none\">\n", qr.size + brd * 2))

with

	.append(String.format("<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" width=\"%1$d\" height=\"%1$d\" viewBox=\"0 0 %1$d %1$d\" stroke=\"none\">\n", qr.size + brd * 2))

in [QrCodeGeneratorDemo.java](https://github.com/nayuki/QR-Code-generator/blob/4c74eea03ee8f961f98a35a45dad64b4e752d74e/java/QrCodeGeneratorDemo.java#L237) because more apps can interpret the content correctly. 

Bests
Gregor

**Comment by nayuki** [comment]
I wasn't totally sure on the behavior of this, so I read up the SVG spec now: https://www.w3.org/TR/SVG11/struct.html#SVGElementWidthAttribute

First of all, the viewBox attribute is critical and can't be omitted, just so we have a common understanding. This determines what part of the virtual infinite vector space should be displayed as a rectangular image.

The width and height attributes on an <svg> element are not essential, as far as I understand. If you don't specify them, the browser will treat them as 100%, which generally means full screen (not always). For example: https://www.nayuki.io/res/triangle-solver-javascript/labelled-triangle-diagram.svg

If you do specify width and height, then the image will be rendered at that specified size by default - say, 600px × 300px. But because the image is *scalable*, I feel that specifying a default pixel size or physical size (in millimetres) makes no sense. My stance is that the consumer of the image - whether it's the web developer who wants to put it on a page, or some graphics application that wants to rasterize the image - who is responsible for specifying what dimensions or how many pixels they want. The SVG image itself has no inherent concept of "pixels" or intrinsic dimensions.

**Comment by olimaticer** [comment]
You are right, you can't please any browser.
