### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by praudmur** [nayuki/QR-Code-generator#124]
Hello!
Is this library supposed to support Cyrillic symbols?(C++ version)

Here's the code - I am trying to encode cyrillic phrase.
```

  const char* text = "Привет МИР";              // User-supplied text
    const QrCode::Ecc errCorLvl = QrCode::Ecc::LOW;  // Error correction level

    //Make and print the QR Code symbol
    const QrCode qr = QrCode::encodeText(text, errCorLvl);
    std::string svg = toSvgString(qr, 4);
```

When decoding - the text  cannot be read(it displays unidentified(chinese?) symbols.

**Comment by manuelbl** [comment]
The library supports the entire Unicode character set including Cyrillic
symbols.

The string passed to `QrCode::encodeText()` needs to be encoded in UTF-8.
Since it doesn't work for you, it's likely that the string is encoded
differently.

The best way to fix the encoding is to use UTF-8 to encode the C++ source
file and to ensure that the compiler uses UTF-8 as both the source and
execution character set.

**Comment by praudmur** [comment]
Thanks, it worked.
