### ISSUE TITLE
Is the decision to remove `BufferedImage` raster bitmap generation permanent? (Java)

### ISSUE THREAD

**Issue by jwr** [nayuki/QR-Code-generator#125]
Commit 010410be0244769db0a1efbc7eb78833e31b85bf removed the support for raster bitmap generation, which was rather useful. I didn't follow the changes carefully, blindly updated to `1.7.0`, and my app broke.

I wanted to know if this is a permanent decision — this was a useful capability, and I will need to basically write the same code again to get a PNG. I even thought about using the code from the demo directly, but it's a private function.

If this is permanent and not coming back, I can certainly re-implement this (or stick with an older version of the library), but I wanted to ask first.

Also, thank you for the very reliable library!

**Comment by nayuki** [comment]
Thank you for the fine question. Yes, the removal of rendering functions in the library is permanent. I thought I explained my intent in the commit log, but it seems like I didn't. See discussion https://github.com/nayuki/QR-Code-generator/issues/120 . Also note that `java.awt.BufferedImage` was causing perennial problems with Android developers, which gave me more reasons to just drop graphics support altogether. And people were pestering me every now and then about custom colors, custom shapes, logo insertion, etc. And never mind the fact that I can never possibly support all reasonably popular graphics formats, third-party libraries, and environments.

I apologize for breaking your build; I thought rendering was a minor feature that not many users were relying on, and this change didn't feel like a "2.0" release which would be required by [Semantic Versioning](https://semver.org/). See discussion https://github.com/nayuki/QR-Code-generator/issues/117 .

Please _steal_ my function [`QrCodeGeneratorDemo.toImage()`](https://github.com/nayuki/QR-Code-generator/blob/c6cbb388a70d2906520a4f15dbd67561aa296da9/java/QrCodeGeneratorDemo.java#L177-L207). It is over-engineered to be pedantically correct and well-documented, because it used to be a library function. I won't even sue for copyright infringement; consider the existing `toImage()` and `toSvgString()` functions to be public domain. In exchange, I will generally refuse unpaid requests to explain, customize, or design new graphics functions.

Thanks for the compliments; I hope I fulfilled the [goal](https://github.com/nayuki/QR-Code-generator/blob/671237fff22b288ddc465ceb71cf92f579113b3e/Readme.markdown#introduction) of:

> This project aims to provide the best and clearest QR Code generator library. The primary goals are flexible options and absolute correctness. The secondary goals are compact implementation size and good documentation comments.

**Comment by jwr** [comment]
Thanks for explaining in detail! I understand the reasoning. Not a big problem, I just wanted to check. I've now re-implemented the function in Clojure.

I think you are fulfilling the goals very well. It is certainly the cleanest and most reliable code I've found. Also, it is great that I can use the same library for both JavaScript and Java versions (client-side with ClojureScript and server-side rendering with Clojure in my case).

One thing that would *really* help people who use your library in larger apps over the long term would be a changelog or release notes. Nothing extensive, so as not to take too much of your time, but a short list of changes that can break applications (such as removing functionality) would help a lot. I looked but couldn't find anything of the kind.

As an app developer, I have tens of dependencies, and every once in a while I go through them and try to figure out which ones need update and what could potentially break as a result. Semantic versioning doesn't really solve that problem, sometimes even relatively minor changes can have big effects in some apps. But a human reading a changelog can quickly understand what needs to be tested and looked at when updating a library.

Once again, thanks for making your code available!
