### ISSUE TITLE
Java version 1.8 is not backward compatible

### ISSUE THREAD

**Issue by manuelbl** [nayuki/QR-Code-generator#139]
The new version 1.8 is not backward compatible with version 1.7. This is in violation of the semantic versioning used by Maven and Gradle, and breaks existing software. Such a change would have been ok if the major version number was increased.

An example of a breaking change is the change from `QrCode.encodeText(String, Ecc)` to `QrCode.encodeText(CharSequence, Ecc)`. While this isn't a problem if the code is recompiled, it affects software using the library indirectly such as my [SwissQRBill](https://github.com/manuelbl/SwissQRBill) library.

Would you accept a PR that fixes the incompatibilities (e.g. by reintroducing `QrCode.encodeText(String, Ecc)` in addition to the new method) and would you quickly release a new version?

**Comment by nayuki** [comment]
Class `java.lang.String` implements interface `java.lang.CharSequence`. Where is the incompatibility?

**Comment by nayuki** [comment]
I see, thanks for the detailed explanation. The thing about Java binary vs. source compatibility makes sense now that you mentioned it (and I read about it in Effective Java), but binary compatibility is essentially never on my mind as a developer. FYI I do publish source libraries on Maven too. What you said about an application having multiple dependencies on one library is an interesting point as well.

Semantic version is too onerous for me to follow. To date, each one of my versioned releases is a minor release in the traditional sense (think of Java 1.0, 1.1, 1.2, etc.), to convey that it's an incremental improvement and not a groundbreaking rewrite that changes how everything is done. Each of my releases is about a year apart and is a major release in the SemVer sense, with some features that are strictly incompatible.

To give examples of my past or future changes that break Semver:

* Changing or removing methods.
* Renaming types/modules/files.
* Changing exception messages or types. I know some developers will parse error strings.
* Changing the QR Code penalty calculation algorithm. The generated QR Code is still scannable, but the exact bits will differ due to the mask pattern changing. So this will break hard-coded test cases.
* Changing the text segmentation algorithm. This means that some previously unencodable texts become encodable or vice versa. This will also break hard-coded test cases.

I apologize for the inconvenience I have caused you. But I really want to keep my codebase clean and minimal and avoid having to explain things like "this function exists here to preserve compatibility with 1.7.0; it wouldn't exist in a rewrite".

See also: https://github.com/nayuki/QR-Code-generator/issues/117

**Comment by manuelbl** [comment]
Ok, understood.

You should probably state on your web site that you are not using semantic versioning for the Java version (as is strongly recommended by Maven Central). It would have help me.
