### ISSUE TITLE
Operator = function is unavailable in qrcodegen::QrSegment

### ISSUE THREAD

**Issue by PhilLab** [nayuki/QR-Code-generator#15]
Thanks for this library!
I could not compile the C++ variant on Visual Studio 2013, 64bit

> error C2582: 'operator =' function is unavailable in 'qrcodegen::QrSegment' (C:\DEVELOPMENT\ioxp.git\src\common\cv\qrcodegen\QrCode.cpp)
 ...
QrCode.cpp(59) : see reference to function template instantiation 'std::vector<qrcodegen::QrSegment,std::allocator<_Ty>>::vector(std::initializer_list<qrcodegen::QrSegment>,const std::allocator<_Ty> &)' being compiled
...
QrCode.cpp(53) : see reference to class template instantiation 'std::vector<qrcodegen::QrSegment,std::allocator<_Ty>>' being compiled

The operator ``=`` is not available because of the non-static const members in ``QrSegment`` and ``QrSegment::Mode``.

**Comment by nayuki** [comment]
That's strange, I can compile the code just fine in GCC and Clang. Maybe the std::vector implementation in VC++ behaves differently? I can't see why the assignment operator would be needed, hmm...

**Comment by nayuki** [comment]
The QR Code generator library, C++ version, has always compiled fine on GCC and Clang. Sorry to hear that you are having troubles in Microsoft Visual C++ 2013.

I did some research and thinking, and it seems you are right. I don't fully understand the situation, but it seems that the instance const fields inhibit the default assignment operator, which is somehow apparently needed for putting that type into an `std::vector`. Some relevant reading:

* https://web.archive.org/web/20121007040734/http://blog.copton.net/archives/2007/10/13/stdvector/index.html
* https://stackoverflow.com/questions/4124271/stdvector-of-objects-and-const-correctness/
* https://stackoverflow.com/questions/4136156/const-member-and-assignment-operator-how-to-avoid-the-undefined-behavior

It seems I copied my Java library's design too much by making the fields const. I will alter the design to make the fields non-const, as well as any other necessary changes. Thanks for your patience.

**Comment by nayuki** [comment]
I made a batch of invasive changes in the recent [commits](https://github.com/nayuki/QR-Code-generator/commits/8bbfa3938bc8af80a00c6ea8dc25aedf06a8eeb0):

* Changed public const instance fields into private non-const fields
* Added public getters for the immutable private fields
* Updated related code to use the new API
* Changed convention to pass `QrCode::Ecc` and `QrSegment::Mode` by value instead of const reference

Please try out the latest library version and tell me how it goes. It should hopefully work in MSVC++ 2013 and other compliant compilers.

**Comment by PhilLab** [comment]
Thanks, this works!
