### ISSUE TITLE
Allow different colors when generating svg

### ISSUE THREAD

**Issue by tnixeu** [nayuki/QR-Code-generator#17]
Currently the colors are fixed to black (#000000) and white (#FFFFFF). Would you accept changes which would allow setting the color?

**Comment by nayuki** [comment]
QR Code symbols are nominally black and white. Other colors are considered artistic but reduce contrast.

**Comment by nayuki** [comment]
QR Code symbols are nominally black and white. Other colors are considered artistic but reduce contrast.

This idea was submitted and discussed by someone else earlier this year. https://github.com/nayuki/QR-Code-generator/pull/3

**Comment by rugk** [comment]
> artistic

Yes, and some users would like it/use the lib for that, so what is wrong with it?

> but reduce contrast.

Of course, when you use the lib, you have to make that sure. That is obvious, but not an argument against the feature in general…

**Comment by rugk** [comment]
BTW in my use case it is simply that it should match the browser theme/design of all other stuff (in my case: in the browser, but in other cases may be the website). 

This here just looks nicer:
![](https://raw.githubusercontent.com/rugk/offline-qr-code/master/assets/screenshots/qrDark.png)

(I am aware that inverted colors cannot be read by all QR code readers)

**Comment by nayuki** [comment]
To be clear, I still do not intend to add color options to the official code distribution. This is because the QR spec mandates black and white. Letting the user choose different colors may mean shooting themselves in the foot in a non-obvious way.

However, anyone is free to copy my [`drawCanvas()`](https://github.com/nayuki/QR-Code-generator/blob/98d1f0cc91d060cbb2cd19a4663e4cfac237cd51/javascript/qrcodegen.js#L152) method into their own application code and modify it to use different fixed or variable colors.

**Comment by rugk** [comment]
> But if the spec says that it has to be black and white

I guess they don't. Would also like to see this, if it exists, but actually many, many QR codes are not b/w.
