### ISSUE TITLE
Invalid encoding with certain strings in C++ version of the code

### ISSUE THREAD

**Issue by jasonob** [nayuki/QR-Code-generator#19]
I've been running into problems with some text strings with the C++ version

I'm running on both x86 and ARM, so its not an architecture issue

Here's how I'm creating the QRCode

```
std::vector<QrSegment> segs = QrSegment::makeSegments(getQRString());
QrCode qr1 = QrCode::encodeSegments(segs, QrCode::Ecc::HIGH);
code = new QrCode(qr1, -1);
MSG("version = %d mask %d ECC %d\n", code->getVersion(), code->getMask(), code->getErrorCorrectionLevel().getOrdinal() )

```
This string will not encode correctly

`This project aims to be the best, clearest library for generating QR Codes. My primary goals are flexible options and`

Encoded on your website, using MEDIUM reports (which generates a correct QRCode) reprots

QR Code version = 7, mask pattern = 6, character count = 117, encoding mode = byte, error correction = level M, data bits = 948

however, the C++ code reports version 4, mask 2, ECC 1

Some strings work fine, but from the testing I've done, it looks like the code incorrectly transitions to different versions at different times to the website version, and encodings will fail

This string works, and reports version 6, mask 2, ECC 1

`This project aims to be the best, clearest library for generating QR Codes. My primary goals`

**Comment by jasonob** [comment]
Turns out the problem was to do with the way I was generating the text string... some stack corruption I think. Closing this issue

**Comment by nayuki** [comment]
Okay, you are probably right. The C++ code snippet shows nothing wrong, so I guess the problem is elsewhere in the code.

All language versions of my QR Code generator library are designed to produce bit-identical output when given the same input values. The way you cross-checked with the JavaScript web version was valid.

Next time, consider building with `-fsanitize=address` to catch memory corruption errors.
