### ISSUE TITLE
/.../QrCode.cpp:400: error: 'INT32_MAX' was not declared in this scope    int32_t minPenalty = INT32_MAX;                         ^

### ISSUE THREAD

**Issue by mrdeveloperdude** [nayuki/QR-Code-generator#2]
Hi!

Got the following compile error:

`/.../QrCode.cpp:400: error: 'INT32_MAX' was not declared in this scope    int32_t minPenalty = INT32_MAX;                         ^
`
For this line: `int32_t minPenalty = INT32_MAX;`
In `int qrcodegen::QrCode::handleConstructorMasking(int mask) `

when building with Android NDK. I think it is easy to fix, but since I am on Qt I will just replace all int32_t with qint32 and matching Qt primitives (to have portability for free), so my fix won't be useable by anyone else.

**Comment by nayuki** [comment]
(Related to http://stackoverflow.com/a/39951669/839689 )

Hello Lennart! A couple of things going on here:

* `INT32_MAX` is defined in stdint.h (a.k.a. cstdint). QrCode.cpp doesn't #include the header file, but it includes QrCode.hpp which does #include \<cstdint>.
* You may replace all `int32_t` with `qint32`, et cetera. My hunch is that this is just extra work without any benefit, because if I understand correctly, stdint.h should be supported pervasively by now.

**Comment by mrdeveloperdude** [comment]
Yes. Im å purist. Bug is that INT32_MAX is not defined in android ndk
toolchain even when <cstdint> is include. So much for pervasively supporter
:p


On Dec 16, 2016 11:44 PM, "Nayuki" <notifications@github.com> wrote:

(Related to http://stackoverflow.com/a/39951669/839689 )

Hello Lennart! A couple of things going on here:

   - INT32_MAX is defined in stdint.h (a.k.a. cstdint). QrCode.cpp doesn't
   #include the header file, but it includes QrCode.hpp which does #include
   <cstdint>.
   - You may replace all int32_t with qint32, et cetera. My hunch is that
   this is just extra work without any benefit, because if I understand
   correctly, stdint.h should be supported pervasively by now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nayuki/QR-Code-generator/issues/2#issuecomment-267714191>,
or mute the thread

**Comment by nayuki** [comment]
That's a troubling discovery. If I understand correctly, INT32_MAX is guaranteed to be in stdint.h, which must be supported if the compiler supports C++11. I suggest two options for you:

* Try writing std::INT32_MAX just in case that symbol is in the std namespace and not in the global namespace.
* Try including stdint.h instead of cstdint.
* Simply write out the constant 2147483647, because INT32_MAX must have the same value on every platform (unlike INT_MAX).

**Comment by mrdeveloperdude** [comment]
Thanks for suggestions!

I already put the constant in, that of course works great :)

I will also try std:: namespace, I did not even think of it. It could
indeed be a problem in my code. I prefer not to use the "using" keyword.

Also recommended is to use <cstdint> in C++ instead of <stdint.h>, usually
the first will include the other (I checked, wrapped in a serious amount of
macro trickery there actually is such an inclusion in Android NDK so that
was kind of puzzling to me. )

Again thanks.

**Comment by nayuki** [comment]
It's okay to avoid using the `using` keyword. For one usage, it's probably better to write out the fully qualified name like `std::INT32_MAX`.

I think you're right that it is recommended to use \<cstdint> instead of \<stdint.h>. It agrees better with C++ conventions.

There is a general confusion about whether items that were defined globally in C are present globally in C++ or must be accessed through namespace `std`. See discussions like this for example: http://stackoverflow.com/questions/32606023/when-using-c-headers-in-c-should-we-use-functions-from-std-or-the-global-na
