### ISSUE TITLE
Request for a minimal hello-world HTML / JS example

### ISSUE THREAD

**Issue by hq6** [nayuki/QR-Code-generator#209]
I looked around your website and github repo and was not able to find a simple HTML and Javascript example (without the need for helper functions that are not in the main library) of generating a QR Code.

In terms of what I did find, [this example](https://github.com/nayuki/QR-Code-generator/blob/master/typescript-javascript/qrcodegen-output-demo.ts) is not JS and is not directly runnable without a typescript compiler, while the [README examples](https://github.com/nayuki/QR-Code-generator/blob/master/typescript-javascript/Readme.markdown) do not include the wrapping HTML and full set of includes required to get hello world running.

Would you consider adding an example equivalent to [this](https://github.com/neocotic/qrious?tab=readme-ov-file#examples)?

**Comment by nayuki** [comment]
> I looked around your website ... and was not able to find a simple HTML and Javascript example

The project's main web page itself is an example. It requires view-source and tracing the compiled JavaScript file, though. https://www.nayuki.io/page/qr-code-generator-library

> [this example](https://github.com/nayuki/QR-Code-generator/blob/master/typescript-javascript/qrcodegen-output-demo.ts) is not JS and is not directly runnable without a typescript compiler

Correct; this is by design. I do not put compiled code in the Git repository. However, you can find pre-compiled code in GitHub releases: https://github.com/nayuki/QR-Code-generator/releases

> the [README examples](https://github.com/nayuki/QR-Code-generator/blob/master/typescript-javascript/Readme.markdown) do not include the wrapping HTML and full set of includes required to get hello world running

This is by design. If you look over past issues and pull requests, I made the decision to not include graphical support out of the box, because output formats are in a constant state of flux and there is no universal format that can withstand the test of time. Hence, I decided to focus the library purely on computation and being able to retrieve a matrix of binary pixels (QR Code "modules"). All the responsibility and complexity of graphical rendering is pushed onto the user of the library by design.

**Comment by hq6** [comment]
Thanks for the response, and I'm glad the omission was intentional rather than accidental.

While I agree that the core library likely does not need graphical capabilities, having a  minimal, self-contained example makes this library easier to evaluate as a user considering which library to use.

Thus, after following your advice and reverse engineering the larger example from your website, I've put up a minimal example here for future people who might be interested in having it:

```
<html>
<head>
<title>QR Code MWE</title>
<script type="text/javascript" src="qrcodegen-v1.8.0-es6.js"></script>
</head>
<body>
<canvas id="qrcode" style="width:300px; height:300px; margin-top:15px;"></canvas>
<div id="debug" style="width:300px; height:300px; margin-top:15px;"></div>

<script type="text/javascript">

window.onload = function() {
    const qr = qrcodegen.QrCode.encodeText("hello world", qrcodegen.QrCode.Ecc.LOW);

    let scale = 10;

    const canvas = document.getElementById("qrcode");
    const width = qr.size * scale;
    canvas.width = width;
    canvas.height = width;
    let ctx = canvas.getContext("2d");
    for (let y = 0; y < qr.size; y++) {
      for (let x = 0; x < qr.size; x++) {
        ctx.fillStyle = qr.getModule(x, y) ? "black" : "white";
        ctx.fillRect(x * scale, y * scale, scale, scale);
      }
    }
}
</script>
</body>
</html>
```

**Comment by irmo322** [comment]
Thank you hq6, this is exactly what I needed :)
