### ISSUE TITLE
TypeError: 'type' object is not subscriptable. Python 3.7.17

### ISSUE THREAD

**Issue by oguma** [nayuki/QR-Code-generator#211]
It worked with Python 3.10.12
but import error occured with Python 3.7.17
```
File "<stdin>", line 1, in <module>
File "qrcodegen.py", line 880, in <module>
  class _BitBuffer(list[int]):
TypeError: 'type' object is not subscriptable
```

So, I changed qrcodegen.py a bit like this, and solved.

```
28a29,30
> from typing import List
> 
880c882,883
< class _BitBuffer(list[int]):
---
> # class _BitBuffer(list[int]):
> class _BitBuffer(List[int]):
```

I get hint from this post.
https://stackoverflow.com/questions/75202610/typeerror-type-object-is-not-subscriptable-python/75202688#75202688

Thank you.

**Comment by nayuki** [comment]
See:

* `from __future__ import annotations` ( https://stackoverflow.com/questions/75202610/typeerror-type-object-is-not-subscriptable-python/78631695#78631695 )
* https://github.com/nayuki/QR-Code-generator/commit/42a886d7845283a048423bd78a82912584325476

**Comment by nayuki** [comment]
Okay, I replicated your problem in a Python 3.7 environment. You are right, the problem is not `from __future__ import annotations`, the problem is `class _BitBuffer(list[int]):`.

You can certainly make this private patch in your copy of the code. But I wouldn't want to support old Python versions in the main code. For reference:

* [Python 3.7](https://www.python.org/downloads/release/python-370/) was released on 2018-06-27 and reached end of life 5 years later in 2023, receiving no security fixes thereafter. https://devguide.python.org/versions/
* [Python 3.9](https://www.python.org/downloads/release/python-390/) was released on 2020-10-05, which is already 4 years ago.

**Comment by oguma** [comment]
OK. Hosting service I use as my main production server only has Python 3.7.17.
I can use qrcodegen.py with this private patch when I run qrcodegen on the production server.
No problem at all.

**Comment by nayuki** [comment]
No problem, thanks for your effort in solving the problem by yourself.
