### ISSUE TITLE
Some warnings

### ISSUE THREAD

**Issue by redmanmale** [nayuki/QR-Code-generator#22]
When compiling with `x86_64-w64-mingw32-gcc (GCC) 6.3.0`

```
$ make
/usr/bin/x86_64-w64-mingw32-gcc.exe -std=c99 -O3 -Wall -fPIC -shared -o libqrcodegen.so qrcodegen.c

qrcodegen.c: In function 'numCharCountBits':
qrcodegen.c:1023:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
qrcodegen.c:1017:83: warning: 'i' may be used uninitialized in this function [-Wmaybe-uninitialized]
   case qrcodegen_Mode_ALPHANUMERIC: { const int temp[] = { 9, 11, 13}; return temp[i]; }
                                                                               ~~~~^~~
qrcodegen.c: In function 'drawFormatBits':
qrcodegen.c:435:14: warning: 'data' may be used uninitialized in this function [-Wmaybe-uninitialized]
  data = data << 3 | (int)mask;  // ecl-derived value is uint2, mask is uint3
         ~~~~~^~~~
qrcodegen.c: In function 'applyMask':
qrcodegen.c:545:4: warning: 'invert' may be used uninitialized in this function [-Wmaybe-uninitialized]
    setModule(qrcode, x, y, val ^ invert);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
qrcodegen.c: In function 'qrcodegen_encodeSegmentsAdvanced':
qrcodegen.c:931:3: warning: 'modeBits' may be used uninitialized in this function [-Wmaybe-uninitialized]
   appendBitsToBuffer(modeBits, 4, qrcode, &bitLen);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by nayuki** [comment]
Thanks for providing the diagnostic information. I understand what the warnings are complaining about.

In all cases mentioned, the uninitialized variable or undefined return value are impossible by design. The undefined case is always covered by an `assert(false);` statement - although assertions can be bypassed, so it could be a no-op instead of stopping the program. I have extensively tested the qrcodegen library to confirm that the `assert(false);` code path is never triggered.

I will have to give some thought about how to fix these compile-time warnings in the most reasonable way. Maybe I'll use `exit(1);`, or give dummy default values, or use an infinite loop.

**Comment by nayuki** [comment]
Fixed in https://github.com/nayuki/QR-Code-generator/commit/30a94745965868cfe79749a5031c2b656c4432d2 . Please try it in your development environment and report back whether the warning messages are gone.

**Comment by redmanmale** [comment]
@nayuki 
All warnings are gone! Thank you!
