### ISSUE TITLE
Enhancement: 3x performance boost using block chars instead of canvas

### ISSUE THREAD

**Issue by systemsplanet** [nayuki/QR-Code-generator#34]
**Updates Per Second**

|Elements|Canvas|Div Block Chars|
|:--|:--|:--|
|1| 30|76|
|8| 3|9 |

**Tested Configuration**

- OS: Windows 10 
- Hardware: Dell XPS27 (3GHz i7  8GB RAM)
- QR Code 
   - Data: 985 random binary chars 
   - Version: 40
   - ECC: LOW
   - Boost Ecc: OFF

** Other Considerations **

- using a single canvas would probably not speed things up since most of the time is spend doing the drawing in drawCanvas
- using a single div would probably speed things up since only one Dom update would be required for N QR codes on the screen
- Canvas can't take advantage of web workers except in [firefox](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/transferControlToOffscreen)

**Code Changes**

Here are the changes to add support for block characters (only tested this with binary data)

1. Add a getter for modules:
```javascript
        this.getModules = function() {  modules; };
```

2. add this method to render using block characters instead of canvas

```javascript
var QRCHARS = (function()  {        // https://en.wikipedia.org/wiki/Block_Elements
  var CHR_SPACE     = '&#x00A0;' ;  // white and white
  var CHR_LOWER     = '&#x2584;' ;  // white and black (Lower half block)		 
  var CHR_UPPER     = '&#x2580;' ;  // black and white (Upper half block)
  var CHR_BLOCK     = '&#x2588;' ;  // black and black (Full block)			  
  var BLOCK_HEIGHT  = 2             // each block char has 2 bits, upper and lower
  
  // imgBitMap[column][row]  true=BLACK, false=WHITE
  var qrCodeChars =  function(imgBitMap) {
    var result        = [];
    var height        = imgBitMap.length;
    var width         = imgBitMap[0].length;
    for(var row = 0; row < height; row += BLOCK_HEIGHT) {                     // blocks are 2 bits tall, top and bottom
      for(var col = 0; col < width; col += 1) {				       
        var bottom = row + 1 < height ? imgBitMap[col][row + 1] : false;      // bottom block is down one row in the image
        result.push( imgBitMap[col][row] ? ( bottom  ? CHR_BLOCK : CHR_UPPER ) : ( bottom  ? CHR_LOWER : CHR_SPACE ) )  ;     
      }
      result.push('<br/>');
    }  
    return result.join(''); 
  }
  return qrCodeChars;
})();
```

3. Style the rendered block chars 
```css
<style>
div {
  font-family:Consolas,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New, monospace;
  font-size:6px;
  line-height:1em; 
  letter-spacing:0em;   
  padding:30px;
  display:inline-block;
}
</style>
```
4. Instead of calling  qr.drawCanvas, render to a div like this:
```javascript
      var el = document.createElement('div');
      el.innerHTML=QRCHARS(qr.getModules())     
```

**Comment by nayuki** [comment]
* Thank you for taking the time to make the detailed write-up, benchmark, and demo code. Unfortunately, I cannot accept this idea (or implement it) for the following reasons.
* The approach that you are suggesting, painting by characters instead of pixels, is fundamentally inexact. Characters are often anti-aliased, with blurry edges and even color subpixel positioning (ClearType, etc.). The sizes and spacing of characters is often inexact. Worse, the behavior is font-dependent, and may depend on what OS the user is running. This is no match for the ideal algorithm, where QR Code modules are painted as exact, razor-sharp squares.
* If you want to go for speed, I would first suggest grabbing the canvas's raw pixel buffer and manually writing uint32 or uint8 values to the array, instead of using high-level drawing routines. See https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas
* Your idea and your code are experimental, and that's fine. Please understand that as the library author, my duty is to deliver correct, stable, well-understood functionality. Even if my approach is not the fastest, I take pride in the elegance of the code (i.e. lacking hacks - unlike how your code is creating divs and such) and in the fact that it always delivers the right data.
* I purposely left QrCode.getModule(x,y) publicly accessible so that you can write your own custom rendering routines.

**Comment by systemsplanet** [comment]
Thank you for your thoughtful reply.

Block characters don't have anti-alias issues. Even if they did, QR error correction would make it mute.

Creating divs using innerHTML is not a hack. It's fast, and how 90% of JS libraries function.

If I get free time, I'll fork and offer people a faster option.
It works awesome for me at three times the speed

Thanks for all the work you did. It was really helpful.

**Comment by systemsplanet** [comment]
can you please set up a paypal acnt so I can send you some cash?
https://www.paypal.me/

bitcoin is not an option at this time.
