### ISSUE TITLE
Pixel-perfect rendering

### ISSUE THREAD

**Issue by rugk** [nayuki/QR-Code-generator#53]
There is a competing QR code generator lib ([kjua](https://github.com/lrsjng/kjua)) that can render QR codes on a canvas in a pixel perfect way.

See https://github.com/lrsjng/kjua/blob/a88369f748926aee8e996e3f720f0f9534c8d86b/src/lib/defaults.js#L5-L6

And as I use your lib for SVG, I can really see the difference.

[comparison.zip](https://github.com/nayuki/QR-Code-generator/files/3123999/comparison.zip)

AFAIK the lib increases the white space for some time, so it really renders in a better way.

Maybe you could implement this, too?

**Comment by nayuki** [comment]
As far as I understand, my raster bitmap output is pixel-perfect too.
Can you describe to me what you mean to draw in a pixel-perfect way?

**Comment by rugk** [comment]
If you look at the comparison (maybe with bigger input data even), you see the difference. It has not as sharp edges as the kjua one…

**Comment by nayuki** [comment]
I think what you are trying to say is that if you know what what pixel size you want the SVG output to be, then you want the elements inside the SVG to align with the pixel grid.

In this case, I think you are missing the point of SVG, which is to not assume that the output has any particular size. If you optimize for one size, you will necessarily dis-optimize for all other sizes - why bother exporting an SVG instead of a raster bitmap?

Also, you are making the assumption that if you fill rectangles in an SVG that happen to align to the output pixel grid, you will get perfectly sharp edges. This assumption is incorrect because an antialiasing algorithm need not have this property; an edge could have a more natural response like Gaussian or sinc.

**Comment by rugk** [comment]
I am only speaking from the user perspective. But I have not tried your Canvas output? Does it possibly use pixel-perfect rendering.

Also tagging @lrsjng to maybe better explain how kjua does this pixel-perfect rendering.

**Comment by rugk** [comment]
Okay, so, I've now created a test website for comparison: https://rugk.github.io/qr-code-libs-test/

You can see that `kjuaCanvasCrisp` somehow cleverly adjusts the size of the QR code and makes it a little smaller.
I wonder how that works… :smiley:

**Comment by rugk** [comment]
You can see that best with small sizes and big input text:
![grafik](https://user-images.githubusercontent.com/11966684/56887461-fa9db900-6a71-11e9-9bc9-3a73beda5f0a.png)

**Comment by nayuki** [comment]
Oh okay, I kind of see. In that case, we should focus on my raster bitmap rendering algorithm, not the vector SVG rendering algorithm.

What you should know is that my QR Code canvas output changes the pixel dimensions the canvas (you can see it plainly in the source code); this simplifies my implementation and reduces computation. My raster rendering is indeed pixel-perfect and crisp, as long as you accept that the size of the canvas can change. What you want to do is to modify the code so that it reads the pixel size of the canvas, computes a scale factor and border offset, and then do the same sort of rendering. I don't think I need to get into the business of autodetecting the user's canvas size and catering to them.

**Comment by rugk** [comment]
Yeah, no detection needed. That said, my use case was this: Given a size X I have available, can this lib fill all that space.

(E.g. see the other issue on the parameter I do not understand: https://github.com/nayuki/QR-Code-generator/issues/54. You can likely do the same calculations, just let me pass in another size.)

---


But getting back to this topic: Yeah, the kjua looks kinda good. Although the kjua-without-crisp looks worse than your canvas output… :thinking: (possibly due to the calculation you mention)

Also, BTW, I wonder why you just don't take the SVG and render it onto a Canvas like this:
https://stackoverflow.com/questions/3768565/drawing-an-svg-file-on-a-html5-canvas#3769883

(Maybe I should include that way in my test website, too? For comparison?)
