### ISSUE TITLE
drawCanvas's scale parameter is confusing

### ISSUE THREAD

**Issue by rugk** [nayuki/QR-Code-generator#54]
`qrElem.drawCanvas(scale, border, canvas);`

The parameters:
* `scale` – I thought `1` would maybe not increase the Camvas, but if you draw the result on 500px, this get's _really_ blurry…
* `border` – Just 0… I mean, this is not the quiet zone, this is a real black border or what? (Don't see a use case for that, but fine.)

Why can't I just pass in the pixel size of my wanted canvas?

---

Looking in the code I see that it somehow calculates the width based on some internal `size`. However, I have no idea what size is set there, as usually this lib is used for SVG generation – but SVGs hardly have a size, they scale… :thinking: (At least the user does not input any size.)

So what do I need to pass in to get a non-blurry canvas for a canvas of a given size?

I've also tried random big numbers, and it seems to fail around > 200 for that parameter.

**Comment by nayuki** [comment]
Disclaimer: I will not attempt to answer all of your questions comprehensively.

The QR Code standard (model 2) defines 40 "version" numbers.

Version 1 uses a 17×17 grid of "modules".
Version 2 uses a 21×21 grid of "modules".

**Comment by nayuki** [comment]
Disclaimer: I will not attempt to answer all of your questions comprehensively.

The QR Code standard (model 2) defines 40 "version" numbers.
Version 1 uses a 21×21 grid of "modules".
Version 2 uses a 25×25 grid of "modules".
Version 3 uses a 29×29 grid of "modules".
Version 4 uses a 33×33 grid of "modules".
... ... ...
Version 40 uses a 177×177 grid of "modules".

Obviously, higher versions have higher data capacity. And we generally want to use the lowest version number that can contain the data we wish to represent.

A single "module" can be rendered with any number of pixels - for example just 1×1, or 5×5, or 200×200. This depends on how you want to map your abstract QR Code onto a physical pixel grid (whether for exporting a bitmap file or directly manipulating pixels on screen).

QR Codes require at least 4 white "modules" surrounding the barcode so that it can be recognized properly. This is what my "border" parameter controls.

**Comment by rugk** [comment]
Ah, okay, thanks. So this is the `this.size` parameter.

Basically, I do not even have many questions. My only one is: What number do I need to use for the `scale` parameter?

Remember  use `encodeText`, so I have no internal knowledge about the QR code or the `size` it chose.

And given a size `X` I want to (approximately) output the given size.

**Comment by rugk** [comment]
Okay, I can calculate it back like this (`qrElem` is the returned QR element):
```js
const scale = width / (qrElem.size + border * 2);
```

I wonder whether we could not put that in the lib itself, so users can input the "width"?

The only problem I have is that it somehow still seems to have little issues with white lines inside of the code:
![grafik](https://user-images.githubusercontent.com/11966684/56950008-bb846c00-6b34-11e9-8d40-1c3ae7745c54.png)

Also, for HiDPI you may multiplicate the scale with 2 and then resize the Canvas, so you have a sharp image anyway. AFAIK…

And for scale > 200 I guess Firefox just gives up… :wink:

**Comment by rugk** [comment]
So what? Is this cumbersome calculation before creating the canvas really the intended way?

And notice how it still has little white lines in between… :thinking:

**Comment by nayuki** [comment]
My rendering algorithms are implemented simply and correctly.

If you want more sophisticated behavior, you are welcome to implement it on your own. Thank you and farewell.

**Comment by laterdayi** [comment]
@rugk   I also want to customize the width and height, but after I try to produce a white border, how do you solve it

**Comment by rugk** [comment]
Well… IIRC I switched to a different library. Here is my test/exploration of different libs: https://github.com/rugk/qr-code-libs-test
