### ISSUE TITLE
Unresolved external symbol while compiling the example with Visual Studio 2017 C++

### ISSUE THREAD

**Issue by JaCkSoN2k** [nayuki/QR-Code-generator#57]
Hello,

I've used the code from the example to try out the library but compiler throws out an error saying there are unsupported external symbols for both of the lines in the example. I've included the directory where the source is located and it does not show any errors regarding the functions or variables.

My code:
```
 #include "stdafx.h"
 #include <string>
 #include <vector>
 #include "QrCode.hpp"
 using namespace qrcodegen;

 int main()
 {
 	// Simple operation
	QrCode qr0 = QrCode::encodeText("Hello, world!", QrCode::Ecc::MEDIUM);
	std::string svg = qr0.toSvgString(4);

	return 0;
}
```

![image](https://user-images.githubusercontent.com/37474542/57183077-58863280-6eb0-11e9-987e-c261c92af266.png)

**Comment by nayuki** [comment]
You wrote a main C++ program and you are trying to use my qrcodegen C++ library.

From the looks of it, it seems that your compiler successfully accessed QrCode.hpp, the header file containing method prototypes like QrCode::encodeText().

My best guess is that you failed to include the class definition files like QrCode.cpp into your compilation process. I think that's why you are getting "unresolved external symbol" errors.

I believe my library is correct and complete, and that this is an issue in your own development environment or configuration. I would like to decline providing any further advice, and refer you to https://stackoverflow.com/questions/ask if you need additional help in solving your problem.

**Comment by JaCkSoN2k** [comment]
I solved it. I had to remove QrCodeGeneratorDemo and QrCodeGeneratorWorker (both had the _main function) files and include the rest by putting them in the solution folder and adding that way. What i did previously was Properties -> VC++ Directories -> Include directories -> Add the files... which wasn't adding the implementation and only the definitions.
