### ISSUE TITLE
No make install (cpp version)

### ISSUE THREAD

**Issue by baerbock** [nayuki/QR-Code-generator#61]
Dear nayuki,

why have you not included an "install" option for the Makefile https://github.com/nayuki/QR-Code-generator/blob/master/cpp/Makefile ?

**Comment by nayuki** [comment]
Because I haven't learned how `make install` works, and because this library is not stable enough to be considered a system library.

**Comment by baerbock** [comment]
@nayuki But isn't it included into LibreOffice with hundreds of millions of users? I don't have a better proof, but what else is [this](https://github.com/LibreOffice/core/blob/b4141cade04dac0c9d47293313a4521282975f12/RepositoryExternal.mk#L4159)?

**Comment by reneengelhard** [comment]
@baerbock 

yes, LibreOffice includes this.
But see the discussion in https://gerrit.libreoffice.org/#/c/73302/

Though @nayuki  is right, this package is not very stable IMHO, let alone because it all is called libqrcodegen.so.1 (which makes them all non-coinstallable and thus Debian seems to have to do https://sources.debian.org/src/qr-code-generator/1.4.0-1/debian/patches/cpp-lib.patch/?hl=25#L25 to have it be able to install parallel.
(This is also what LibreOffice checks against right now.)

**Comment by reneengelhard** [comment]
if there will be a make install; it should be for libqrcodegencpp (see my previous comment)

**Comment by nayuki** [comment]
This is all way over my head, but thanks for the commentary!

**Comment by reneengelhard** [comment]
In a nutshell: see https://github.com/nayuki/QR-Code-generator/issues/63

**Comment by reneengelhard** [comment]
and note the referenced patch implements make install :-)
