### ISSUE TITLE
C4458 warnings in QrCode.cpp

### ISSUE THREAD

**Issue by kirillkovalenko** [nayuki/QR-Code-generator#70]
While compiling current master using VS2019 I'm getting the following warnings:

```none
QrCode.cpp(262,39): warning C4458: declaration of 'mask' hides class member
QrCode.hpp(129,15): message : see declaration of 'qrcodegen::QrCode::mask'
QrCode.cpp(413,34): warning C4458: declaration of 'mask' hides class member
QrCode.hpp(129,15): message : see declaration of 'qrcodegen::QrCode::mask'
```

**Comment by nayuki** [comment]
Not a problem. The code is correct.

**Comment by kirillkovalenko** [comment]
Good, but maybe it's a good thing to rename method parameter to avoid the conflict with a class member's name?

**Comment by nayuki** [comment]
Short answer: Maybe.

Long answer: The code matches the design I have in mind, and it functions correctly in practice. The phenomenon of variable shadowing is well-defined in C++ (Java, JavaScript, Python, etc.), so all compilers are guaranteed to interpret the code in the way I intended. The only downside is that the shadowing may confuse humans who are studying or editing the code. I did notice this variable shadowing warning about a month ago when I compiled my codebase under a very strict set of compiler warnings, but I decided not to take corrective action because it is not a functional deficiency, only a potential deficiency in human clarity. So my verdict is that I will review, at some unspecified point in the future, whether this shadowing is a problem, and then possibly change the naming in all 6 language versions so that all the language ports are synchronized.

**Comment by kirillkovalenko** [comment]
Point taken. 

Just keep in mind that there are a lot of projects nowadays that have '/WX (Treat Linker Warnings as Errors)' option enabled. So, each individual user of your code in such environments have to modify the code anyway.

**Comment by nayuki** [comment]
Understood, I'll take that into consideration. I don't have MSVC installed so that's why I don't know what warnings it has by default. I only compile with GCC and Clang because they're convenient.

**Comment by nayuki** [comment]
Fully fixed in https://github.com/nayuki/QR-Code-generator/commit/67c62461d380352500fc39557fd9f046b7fe1d18 .
