### ISSUE TITLE
[rust/C++] use unsigned integers for module indexing and Qr size

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [nayuki/QR-Code-generator#97]
The size of a Qr code is always positive, I don't see the point of storing it as a signed integer.

I propose that the type of the size variables be changed to "uint32_t" for the C++ version and "u32" for the Rust version.
(Same thing for the parameters of the getModule/get_module function).

This would eleminate the need to check whether or not the parameters of this function are negative and make it easier to work with the Image crate in Rust (pixel indexing in this lib is done using u32s).

**Comment by nayuki** [comment]
There are many facets to this topic of using unsigned integers, but my short answer is a firm **no**.

You come with the best intentions with the observation that sizes are never negative, so they deserve to be stored in unsigned variables. Reality is more complicated than this.

* I specifically designed the `get_module(x, y)` API to return white for out-of-bounds coordinates and allow negative numbers so that you can easy implement border padding.
* Negative numbers are completely reasonable when laying out picture elements in an infinite virtual space, and then clipping that to a finite rectangle only upon final rendering.
* Signed integers have more functionality than unsigned integers. I have argued that Java was correct to omit unsigned integer types (and wish Rust did too) - https://www.nayuki.io/page/unsigned-int-considered-harmful-for-java . I highly recommend you to read this article in full.
* In C/C++, using `uint32_t` can be deceptive. If the native `int` type is actually 64 bits wide, then any arithmetic involving `uint32_t` would get promoted to `signed int` first and conducted using the rules of signed arithmetic, with undefined behavior for overflows. So actually the safest thing to do in C/C++ is to use `int` which is guaranteed to be at least 16 bits wide, and **strictly** ensure that all numbers and intermediate results fit in the range [-32767, 32767].
* Eliminating the negative check is beneficial but doesn't outweigh the other disadvantages. For instance, QR Code versions range from 1 to 40 inclusive, and there isn't a native type that describes this range precisely.
