### ISSUE TITLE
micro Qr support

### ISSUE THREAD

**Issue by edwardocano** [nayuki/QR-Code-generator#98]
hi! do you plan to add micro qr to your library?

**Comment by nayuki** [comment]
Although I read the Micro QR Code section of the specification and understand the general effort needed to implement it, unfortunately the answer is no, for a variety of reasons:

* I have literally never seen a Micro QR Code out in the wild.
* The app I use (Android, Barcode Scanner, using ZXing library) doesn't seem to support scanning it.
* Micro QR has its own rules for stuff like the layout of function patterns, format bits, masks, error correction levels, supported segment modes. It requires a lot of custom code for little benefit. Whereas support QR Code versions 1 through 40 is pretty straightforward because they follow a pattern.

While we're on the topic of unpopular barcode formats, I've also skimmed the spec for the legacy QR Code *Model 1*. I would consider that an exercise to implement for historical completeness, just like Micro QR Codes - not for practical applications.

**Comment by edwardocano** [comment]
Ok, thanks for your answare.
