### ISSUE TITLE
Trying to scan with Google lens

### ISSUE THREAD

**Issue by briancullinan** [nayuki/QR-Code-generator#99]
I can't get any combination from the examples to scan with Google Lens. What am I missing? It works on other QR codes.

Edit: my mistake, it requires a white border around the edge. I don't know if this is common in other libraries, but now it works. The white border is not included in the modules. Maybe that is a good change?

**Comment by nayuki** [comment]
I was almost going to ask you for a test case, but you've solved your own problem. Indeed, you must have at least 1 module of border in order for a QR Code to be scannable; I tested with Android Barcode Scanner (powered by the ZXing library).

Your allegation is half wrong. The examples in my QrCodeGeneratorDemo do produce a white border. I don't know how you managed to have no border.

The reason that I let the amount of border be configurable all the way down to zero is because someone might take a bare QR Code and put it into a web or paper page design that includes the designer's definition of how much border they want.
